name: Run Node.js Scripts

on:
  push:
    branches:
      - master  # or 'main' if that is your branch

jobs:
  run-node-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: firebase-fetcher

      - name: Decode Firebase Service Account Key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > serviceAccountKey.json
        working-directory: firebase-fetcher

      - name: Run fetchKeywords.js
        run: node fetchKeywords.js
        working-directory: firebase-fetcher

      - name: Run Gkeywordresult.js (after fetchKeywords)
        run: node Gkeywordresult.js
        working-directory: firebase-fetcher
